---
title: "Introduction to Machine Learning - Lab 4"
author: "Gustav Sternelöv"
date: "Wednesday, November 11, 2015"
output:
  pdf_document:
    fig_height: 4
    fig_width: 7
---

## Assigment 1
```{r,echo=FALSE}
state <- read.csv("C:/Users/Gustav/Documents/Machine-Learning/Lab 4/State.csv", sep=";")
```

### 1.1

```{r, echo=FALSE}
library(ggplot2)
ggplot(state, aes(x=MET, y=EX)) + geom_point()
```


### 1.2

```{r, echo=FALSE}
library(tree)
set.seed(12345)
fit2 <- tree(EX ~ MET, data=state, control=tree.control(nobs=48, minsize=2))
cv_fit <- cv.tree(fit2)
plot(cv_fit$size, cv_fit$dev, type="b")
```


```{r, echo=FALSE}
pruneFit2 <- prune.tree(fit2, best=3)
plot(pruneFit2)
text(pruneFit2, pretty=0)
```


```{r, echo=FALSE}
cv_pred <- predict(pruneFit2)
par(mfrow=c(1,2))
plot(state$MET, state$EX, col="blue")
points(state$MET, cv_pred, col="red")
fit2_resid <- state$EX - cv_pred
hist(fit2_resid, breaks=14)   
par(mfrow=c(1,1))
```


### 1.3


```{r, echo=FALSE}
# 1.3 
# Non-parametric bootstrap
# 95 % confidence bands
library(boot)
data2=state[order(state$MET),]#reordering data according to MET
# computing bootstrap samples
f=function(data, ind){
  data1=data[ind,]# extract bootstrap sample
  #fit regression tree
  res=tree(EX ~ MET, data=data1, control=tree.control(nobs=48, minsize=2)) 
  #predict values for all Area values from the original data
  priceP=predict(res,newdata=data2)
  return(priceP)
}
res=boot(data2, f, R=1000) #make bootstrap

# Create lower and upper bound. 
e=envelope(res) 

fit=prune.tree(fit2, best=3) 
priceP=predict(fit)

plot(state$MET, state$EX, pch=21, bg="black", col="red")
points(data2$MET,priceP,type="l", col="blue") #plot fitted line
#plot cofidence bands
points(data2$MET,e$point[2,], type="l", col="red", lwd=2)
points(data2$MET,e$point[1,], type="l", col="red", lwd=2)

```


### 1.4


```{r, echo=FALSE, warning=FALSE}
# Parametric bootstrap
# 95 % confidence and prediction bands
# Assumes that Y follows the normal distribution
mle=prune.tree(fit2, best=3)
rng=function(data, mle) {
  data1=data.frame(EX=data$EX,
                   MET=data$MET, data=data)
  n=length(data$EX)
  data1$EX=rnorm(n,predict(mle,newdata=data1),sd(mle$y))
  return(data1)
}
f1=function(data1){
  res=tree(EX ~ MET, data=data1, control=tree.control(nobs=48, minsize=2)) 
  predictedP=predict(res, newdata=data2)
  return(predictedP)
}
res=boot(data2, statistic=f1, R=1000, mle=mle, ran.gen=rng , sim="parametric") 
e2=envelope(res) 
fit=prune.tree(fit2, best=3) 
pred2=predict(fit)
plot(state$MET, state$EX, pch=21, bg="black", col="red", ylim=c(100, 550))
points(data2$MET,pred2,type="l", col="blue") #plot fitted line
#plot cofidence bands
points(data2$MET,e2$point[2,], type="l", col="red", lwd=2)
points(data2$MET,e2$point[1,], type="l", col="red", lwd=2)
```


### 1.5



## Assignment 2

